using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace layeredFundRaiserSystem.Models
{
    public class JoinUserLogin_UserInfo
    {
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string AutoGeneratedLink { get; set; }
        public System.DateTime UserCreationDate { get; set; }
        public string Status { get; set; }

        public int UserInformationId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string ContactNo { get; set; }
        public string NationalId { get; set; }
        public string Country { get; set; }
        public string ProfilePicture { get; set; }
    }
}